
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */
/* %if-c-only */
/* %if-not-reentrant */

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */

/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* begin standard C++ headers. */
/* %if-c++-only */
/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */
/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */
/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */
/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

/* %endif */

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 98
#define YY_END_OF_BUFFER 99
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[265] =
    {   0,
        0,    0,    0,    0,   99,   97,   96,   95,   83,   97,
       89,   82,   97,   77,   78,   87,   86,   74,   85,   81,
       88,   42,   42,   75,   71,   90,   76,   91,   94,   39,
       39,   79,   80,   92,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       72,   93,   73,   84,   88,    4,    6,    5,   70,    0,
       47,    0,   56,   73,   65,   57,    0,    0,   53,   62,
       51,   63,   52,   64,    0,   45,    2,   55,   46,   41,
        0,   42,    0,   42,   80,   72,   79,   61,   67,   69,
       68,   60,   39,    0,    0,   58,   39,   39,   39,   39,

       39,   39,   14,   39,   39,   39,   39,   39,   39,   22,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   59,   66,    1,    4,    3,   43,   48,    0,
       45,   45,    0,   46,   41,    0,   44,   40,   50,   49,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   20,   39,   23,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,    0,
        1,    0,   45,    0,   45,    0,   46,   44,   40,    7,
       39,    9,   10,   39,   39,   39,   39,   16,   17,   39,
       39,   21,   24,   39,   39,   39,   39,   39,   39,   39,

       39,   39,   39,   39,   36,   39,   39,    0,    0,   45,
        8,   11,   39,   39,   39,   39,   19,   39,   39,   27,
       39,   39,   39,   39,   39,   39,   34,   39,   39,   38,
        0,   39,   39,   15,   18,   39,   26,   28,   29,   30,
       31,   32,   39,   39,   39,    0,   39,   13,   39,   33,
       39,   39,    0,   12,   25,   35,   37,    0,    0,    0,
        0,    0,   54,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   25,   25,   25,   26,   27,
       28,   28,   28,   28,   28,   29,   28,   28,   28,   28,
       28,   28,   28,   28,   30,   28,   28,   31,   28,   28,
       32,   33,   34,   35,   28,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   28,   45,   46,   47,   48,
       49,   50,   28,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        4,    1,    1,    1,    1,    1,    5,    5,    1,    1,
        1,    1,    1,    1,    5,    5,    5,    6,    6,    6,
        6,    1,    1,    1,    1,    5,    5,    5,    5,    5,
        5,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    1,
        1,    1,    1
    } ;

static const flex_int16_t yy_base[272] =
    {   0,
        0,  395,   61,   62,  410,  412,  412,  412,  387,   61,
       45,   62,  375,  412,  412,  385,   58,  412,   60,   60,
       65,   80,   73,  383,  412,   86,  383,   63,  412,    0,
       88,  412,  412,  382,  349,  351,   79,   72,   68,   55,
      352,   76,  351,  359,   86,  340,  349,  347,  352,  336,
      412,   57,  412,  412,  122,    0,  412,  377,  412,  118,
      412,  389,  412,  412,  412,  412,  123,  132,  412,  412,
      412,  412,  412,  412,  376,  128,  412,  412,  132,  162,
      148,  141,    0,  167,  412,  412,  412,  368,  412,  412,
      412,  367,    0,  131,  355,  412,  334,  346,  333,  348,

      335,  341,  327,  328,  325,  325,  328,  325,  322,    0,
      321,  325,   47,  323,  139,   96,  327,  320,  123,   97,
      325,  349,  412,  412,    0,    0,  412,  412,  412,  187,
      412,  193,  200,  412,  194,  135,  208,  198,  412,  412,
      318,  330,  325,  313,  137,  327,  325,  321,  313,  319,
      322,    0,  308,    0,  314,  311,  300,  302,  304,  311,
      297,  295,  295,  307,  297,  301,  305,  307,  296,  322,
        0,  212,  214,  233,  412,  239,  241,  412,  232,    0,
      295,    0,    0,  286,  294,  283,  290,    0,    0,  284,
      281,    0,    0,  281,  281,  278,  290,  280,  284,  289,

      284,  279,  268,  267,    0,  240,  252,  245,  246,  248,
        0,    0,  242,  242,  245,  236,    0,  230,  233,    0,
      241,  238,  238,  221,  230,  232,    0,  223,  225,    0,
      218,  199,  193,    0,    0,  202,    0,    0,    0,    0,
        0,    0,  197,  196,  169,  171,  166,    0,  152,    0,
      161,  154,  150,    0,    0,    0,    0,  130,  132,  114,
      100,   74,  412,  412,  294,  300,  306,  308,  314,   66,
      320
    } ;

static const flex_int16_t yy_def[272] =
    {   0,
      264,    1,  265,  265,  264,  264,  264,  264,  264,  266,
      264,  264,  267,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  268,
      268,  264,  264,  264,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      264,  264,  264,  264,  264,  269,  264,  264,  264,  266,
      264,  266,  264,  264,  264,  264,  267,  267,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  270,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  268,  266,  267,  264,  268,  268,  268,  268,

      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  264,  264,  271,  269,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  270,  264,  264,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  264,
      271,  264,  264,  264,  264,  264,  264,  264,  264,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,

      268,  268,  268,  268,  268,  268,  268,  264,  264,  264,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      264,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  264,  268,  268,  268,  268,
      268,  268,  264,  268,  268,  268,  268,  264,  264,  264,
      264,  264,  264,    0,  264,  264,  264,  264,  264,  264,
      264
    } ;

static const flex_int16_t yy_nxt[476] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   30,   30,   30,   31,   30,
       30,   32,    6,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   30,   42,   30,   43,   30,   30,   30,   30,
       44,   45,   46,   47,   48,   49,   30,   50,   30,   51,
       52,   53,   54,   57,   57,   61,   63,   64,   65,   70,
      138,   58,   58,   72,   75,   77,   76,   76,  123,   71,
      263,   73,   74,   66,   91,   92,   78,   79,  156,   84,
       84,   86,   94,   62,   79,   95,   80,   80,   81,  157,

      107,   82,   82,  108,   87,   81,   88,   89,   82,   82,
       83,  102,   81,  104,   99,  105,  110,  124,   82,   81,
      103,  100,   61,  111,  106,   82,   82,  101,  114,  115,
      128,  161,   77,   82,  264,   61,   83,  125,  116,   67,
      167,  117,  168,   78,   76,   76,  162,  262,  132,  132,
       62,  137,  137,  130,  131,   68,  131,  133,  134,  136,
      134,  136,  261,   62,  137,  137,  165,  130,  131,   82,
       82,  133,  134,  131,  166,  260,   79,  134,   80,   80,
      159,   79,  259,   84,   84,  258,   82,   81,  184,  185,
      135,  135,   81,  257,   82,   82,   82,  160,  172,  256,

      172,   81,  255,  173,  173,  254,   81,  135,  253,  132,
      132,  176,   82,  176,  252,  135,  177,  177,  174,  175,
       82,  175,  135,  135,  137,  137,  179,  179,  173,  173,
      173,  173,  174,  175,  178,  251,  178,  250,  175,  135,
      131,  249,  131,  179,  209,  248,  209,  135,  178,  210,
      210,  179,  247,  178,  131,  177,  177,  177,  177,  131,
      179,  179,  210,  210,  210,  210,  246,  134,  245,  134,
      244,  243,  242,  241,  175,  240,  175,  179,  239,  238,
      237,  134,  236,  235,  234,  179,  134,  233,  175,  232,
      231,  230,  229,  175,   56,   56,   56,   56,   56,   56,

       60,   60,   60,   60,   60,   60,   67,   67,  228,   67,
       67,   67,   93,   93,  126,  227,  126,  226,  126,  126,
      171,  225,  171,  171,  171,  171,  224,  223,  222,  221,
      220,  219,  218,  217,  216,  215,  214,  213,  212,  211,
      208,  207,  206,  205,  204,  203,  202,  201,  200,  199,
      198,  197,  196,  195,  194,  193,  192,  191,  190,  189,
      188,  187,  186,  183,  182,  181,  180,  170,  169,  164,
      163,  158,  155,  154,  153,  152,  151,  150,  149,  148,
      147,  146,  145,  144,  143,  142,  141,   68,  140,  139,
      129,  264,  127,  122,  121,  120,  119,  118,  113,  112,

      109,   98,   97,   96,   90,   85,   69,   68,   59,  264,
       55,    5,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264
    } ;

static const flex_int16_t yy_chk[476] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,   10,   11,   11,   12,   17,
      270,    3,    4,   19,   20,   21,   20,   20,   52,   17,
      262,   19,   19,   12,   28,   28,   21,   23,  113,   23,
       23,   26,   31,   10,   22,   31,   22,   22,   23,  113,

       40,   23,   23,   40,   26,   22,   26,   26,   22,   22,
       22,   38,   23,   39,   37,   39,   42,   52,   23,   22,
       38,   37,   60,   42,   39,   22,   23,   37,   45,   45,
       67,  116,   55,   22,   68,   94,   22,   55,   45,   68,
      120,   45,  120,   55,   76,   76,  116,  261,   79,   79,
       60,  136,  136,   76,   76,   67,   76,   79,   79,   81,
       79,   81,  260,   94,   81,   81,  119,   76,   76,   82,
       82,   79,   79,   76,  119,  259,   80,   79,   80,   80,
      115,   84,  258,   84,   84,  253,   82,   80,  145,  145,
       80,   80,   84,  252,   82,   84,   84,  115,  130,  251,

      130,   80,  249,  130,  130,  247,   84,   80,  246,  132,
      132,  133,   84,  133,  245,   80,  133,  133,  132,  132,
       84,  132,  135,  135,  137,  137,  138,  138,  172,  172,
      173,  173,  132,  132,  137,  244,  137,  243,  132,  135,
      173,  236,  173,  138,  174,  233,  174,  135,  137,  174,
      174,  138,  232,  137,  173,  176,  176,  177,  177,  173,
      179,  179,  209,  209,  210,  210,  231,  177,  229,  177,
      228,  226,  225,  224,  210,  223,  210,  179,  222,  221,
      219,  177,  218,  216,  215,  179,  177,  214,  210,  213,
      208,  207,  206,  210,  265,  265,  265,  265,  265,  265,

      266,  266,  266,  266,  266,  266,  267,  267,  204,  267,
      267,  267,  268,  268,  269,  203,  269,  202,  269,  269,
      271,  201,  271,  271,  271,  271,  200,  199,  198,  197,
      196,  195,  194,  191,  190,  187,  186,  185,  184,  181,
      170,  169,  168,  167,  166,  165,  164,  163,  162,  161,
      160,  159,  158,  157,  156,  155,  153,  151,  150,  149,
      148,  147,  146,  144,  143,  142,  141,  122,  121,  118,
      117,  114,  112,  111,  109,  108,  107,  106,  105,  104,
      103,  102,  101,  100,   99,   98,   97,   95,   92,   88,
       75,   62,   58,   50,   49,   48,   47,   46,   44,   43,

       41,   36,   35,   34,   27,   24,   16,   13,    9,    5,
        2,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static const flex_int16_t yy_rule_linenum[98] =
    {   0,
       40,   41,   42,   43,   44,   45,   48,   49,   50,   51,
       52,   53,   54,   55,   56,   57,   58,   59,   60,   61,
       62,   63,   64,   65,   66,   67,   68,   69,   70,   71,
       72,   73,   74,   75,   76,   77,   78,   79,   81,   83,
       84,   85,   86,   88,   89,   90,   92,   94,   95,   96,
       97,   98,   99,  100,  101,  102,  103,  104,  105,  106,
      107,  108,  109,  110,  111,  112,  113,  114,  115,  116,
      117,  118,  119,  120,  121,  122,  123,  124,  125,  126,
      127,  128,  129,  130,  131,  132,  133,  134,  135,  136,
      137,  138,  139,  140,  141,  142,  143

    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "mcc.lex"
#line 2 "mcc.lex"
#include <string>
#include <cstring>
#include "driver.h"
#include "mcc_c.tab.h"
#line 736 "lex.yy.c"
#define YY_NO_INPUT 1
#line 10 "mcc.lex"
  // A number symbol corresponding to the value in S.
  // Code run each time a pattern is matched.
  # define YY_USER_ACTION  loc.columns (yyleng);
#line 742 "lex.yy.c"

#line 24 "mcc.lex"
void count();
yy::parser::symbol_type check_type(driver & drv,const std::string & s,const yy::parser::location_type &loc);
yy::parser::symbol_type make_IDENTIFIER(const std::string & s,const yy::parser::location_type &loc);
yy::parser::symbol_type make_STRING_LITERAL(const std::string &s,const yy::parser::location_type&loc);
yy::parser::symbol_type make_CINT(const std::string &s,const yy::parser::location_type&loc);
yy::parser::symbol_type make_CFLOAT(const std::string &s,const yy::parser::location_type&loc);
#line 751 "lex.yy.c"
#line 752 "lex.yy.c"

#define INITIAL 0
#define IN_COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals ( void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

/* %not-for-header */
#ifndef YY_NO_UNPUT
    
#endif
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */
/* %ok-for-header */

/* %not-for-header */
/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/* %not-for-header */
/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
/* %% [7.0] user's declarations go here */
#line 32 "mcc.lex"


#line 35 "mcc.lex"
  // A handy shortcut to the location held by the driver.
  yy::location& loc = drv.location;
  // Code run each time yylex is called.
  loc.step ();

#line 1043 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 265 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 264 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 98 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 98 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 99 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 40 "mcc.lex"

	YY_BREAK
case 2:
YY_RULE_SETUP
#line 41 "mcc.lex"
BEGIN(IN_COMMENT);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 42 "mcc.lex"
BEGIN(INITIAL);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 43 "mcc.lex"
// eat comment in chunks
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 44 "mcc.lex"
// eat the lone star
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 45 "mcc.lex"
loc.lines();
	YY_BREAK
case YY_STATE_EOF(IN_COMMENT):
#line 46 "mcc.lex"
std::cerr<<"Warning: Could not match /* with */ at "<<loc<<std::endl; BEGIN(INITIAL);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 48 "mcc.lex"
{ count(); return yy::parser::make_AUTO(loc); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 49 "mcc.lex"
{ count(); return yy::parser::make_BREAK(loc); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 50 "mcc.lex"
{ count(); return yy::parser::make_CASE(loc); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 51 "mcc.lex"
{ count(); return yy::parser::make_CHAR(loc); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 52 "mcc.lex"
{ count(); return yy::parser::make_CONST(loc); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 53 "mcc.lex"
{ count(); return yy::parser::make_CONTINUE(loc); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 54 "mcc.lex"
{ count(); return yy::parser::make_DEFAULT(loc); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 55 "mcc.lex"
{ count(); return yy::parser::make_DO(loc);  }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 56 "mcc.lex"
{ count(); return yy::parser::make_DOUBLE(loc); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 57 "mcc.lex"
{ count(); return yy::parser::make_ELSE(loc); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 58 "mcc.lex"
{ count(); return yy::parser::make_ENUM(loc); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 59 "mcc.lex"
{ count(); return yy::parser::make_EXTERN(loc); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 60 "mcc.lex"
{ count(); return yy::parser::make_FLOAT(loc);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 61 "mcc.lex"
{ count(); return yy::parser::make_FOR(loc); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 62 "mcc.lex"
{ count(); return yy::parser::make_GOTO(loc); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 63 "mcc.lex"
{ count(); return yy::parser::make_IF(loc); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 64 "mcc.lex"
{ count(); return yy::parser::make_INT(loc); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 65 "mcc.lex"
{ count(); return yy::parser::make_LONG(loc); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 66 "mcc.lex"
{ count(); return yy::parser::make_REGISTER(loc); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 67 "mcc.lex"
{ count(); return yy::parser::make_RETURN(loc); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 68 "mcc.lex"
{ count(); return yy::parser::make_SHORT(loc); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 69 "mcc.lex"
{ count(); return yy::parser::make_SIGNED(loc); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 70 "mcc.lex"
{ count(); return yy::parser::make_SIZEOF(loc); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 71 "mcc.lex"
{ count(); return yy::parser::make_STATIC(loc); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 72 "mcc.lex"
{ count(); return yy::parser::make_STRUCT(loc); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 73 "mcc.lex"
{ count(); return yy::parser::make_SWITCH(loc); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 74 "mcc.lex"
{ count(); return yy::parser::make_TYPEDEF(loc); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 75 "mcc.lex"
{ count(); return yy::parser::make_UNION(loc); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 76 "mcc.lex"
{ count(); return yy::parser::make_UNSIGNED(loc); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 77 "mcc.lex"
{ count(); return yy::parser::make_VOID(loc); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 78 "mcc.lex"
{ count(); return yy::parser::make_VOLATILE(loc); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 79 "mcc.lex"
{ count(); return yy::parser::make_WHILE(loc); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 81 "mcc.lex"
{ count(); return check_type(drv,yytext,loc); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 83 "mcc.lex"
{ count(); return make_CINT(yytext,loc); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 84 "mcc.lex"
{ count(); return make_CINT(yytext,loc); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 85 "mcc.lex"
{ count(); return make_CINT(yytext,loc); }
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 86 "mcc.lex"
{ count(); return yy::parser::make_CONSTANT({mcc::Primitive::Char,0,true,true,false},loc); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 88 "mcc.lex"
{ count(); return make_CFLOAT(yytext,loc); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 89 "mcc.lex"
{ count(); return make_CFLOAT(yytext,loc); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 90 "mcc.lex"
{ count(); return make_CFLOAT(yytext,loc); }
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 92 "mcc.lex"
{ count(); return make_STRING_LITERAL(yytext,loc); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 94 "mcc.lex"
{ count(); return yy::parser::make_ELLIPSIS(loc); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 95 "mcc.lex"
{ count(); return yy::parser::make_RIGHT_ASSIGN(loc); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 96 "mcc.lex"
{ count(); return yy::parser::make_LEFT_ASSIGN(loc); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 97 "mcc.lex"
{ count(); return yy::parser::make_ADD_ASSIGN(loc); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 98 "mcc.lex"
{ count(); return yy::parser::make_SUB_ASSIGN(loc); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 99 "mcc.lex"
{ count(); return yy::parser::make_MUL_ASSIGN(loc); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 100 "mcc.lex"
loc = drv.location;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 101 "mcc.lex"
{ count(); return yy::parser::make_DIV_ASSIGN(loc); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 102 "mcc.lex"
{ count(); return yy::parser::make_MOD_ASSIGN(loc); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 103 "mcc.lex"
{ count(); return yy::parser::make_AND_ASSIGN(loc); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 104 "mcc.lex"
{ count(); return yy::parser::make_XOR_ASSIGN(loc); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 105 "mcc.lex"
{ count(); return yy::parser::make_OR_ASSIGN(loc); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 106 "mcc.lex"
{ count(); return yy::parser::make_SHR(loc); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 107 "mcc.lex"
{ count(); return yy::parser::make_SHL(loc); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 108 "mcc.lex"
{ count(); return yy::parser::make_INC(loc); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 109 "mcc.lex"
{ count(); return yy::parser::make_DEC(loc); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 110 "mcc.lex"
{ count(); return yy::parser::make_PTR(loc); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 111 "mcc.lex"
{ count(); return yy::parser::make_LAND(loc); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 112 "mcc.lex"
{ count(); return yy::parser::make_LOR(loc); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 113 "mcc.lex"
{ count(); return yy::parser::make_LEQ(loc); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 114 "mcc.lex"
{ count(); return yy::parser::make_GEQ(loc); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 115 "mcc.lex"
{ count(); return yy::parser::make_EQ(loc); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 116 "mcc.lex"
{ count(); return yy::parser::make_NEQ(loc); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 117 "mcc.lex"
{ count(); return yy::parser::make_SEMI(loc); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 118 "mcc.lex"
{ count(); return yy::parser::make_L_CURLY(loc); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 119 "mcc.lex"
{ count(); return yy::parser::make_R_CURLY(loc); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 120 "mcc.lex"
{ count(); return yy::parser::make_COMMA(loc); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 121 "mcc.lex"
{ count(); return yy::parser::make_COL(loc); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 122 "mcc.lex"
{ count(); return yy::parser::make_ASS(loc); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 123 "mcc.lex"
{ count(); return yy::parser::make_LEFT_PAR(loc); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 124 "mcc.lex"
{ count(); return yy::parser::make_RIGHT_PAR(loc); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 125 "mcc.lex"
{ count(); return yy::parser::make_L_SQBR(loc); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 126 "mcc.lex"
{ count(); return yy::parser::make_R_SQBR(loc); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 127 "mcc.lex"
{ count(); return yy::parser::make_DOT(loc); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 128 "mcc.lex"
{ count(); return yy::parser::make_AND(loc); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 129 "mcc.lex"
{ count(); return yy::parser::make_NOT(loc); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 130 "mcc.lex"
{ count(); return yy::parser::make_FLIP(loc); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 131 "mcc.lex"
{ count(); return yy::parser::make_MINUS(loc); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 132 "mcc.lex"
{ count(); return yy::parser::make_PLUS(loc); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 133 "mcc.lex"
{ count(); return yy::parser::make_MUL(loc); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 134 "mcc.lex"
{ count(); return yy::parser::make_DIV(loc); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 135 "mcc.lex"
{ count(); return yy::parser::make_MOD(loc); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 136 "mcc.lex"
{ count(); return yy::parser::make_LE(loc); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 137 "mcc.lex"
{ count(); return yy::parser::make_GE(loc); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 138 "mcc.lex"
{ count(); return yy::parser::make_XOR(loc); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 139 "mcc.lex"
{ count(); return yy::parser::make_OR(loc); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 140 "mcc.lex"
{ count(); return yy::parser::make_Q_MARK(loc); }
	YY_BREAK
case 95:
/* rule 95 can match eol */
YY_RULE_SETUP
#line 141 "mcc.lex"
{ count();loc.lines(); }
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 142 "mcc.lex"
{ count(); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 143 "mcc.lex"
{ /* ignore bad characters */ }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 144 "mcc.lex"
return yy::parser::make_END(loc);
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 145 "mcc.lex"
ECHO;
	YY_BREAK
#line 1623 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
/* %endif */
/* %if-c++-only */
/* %endif */
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */
    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 265 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 265 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 264);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */

/* %endif */
#endif

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/* %if-c++-only */
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
/* %endif */
/* %if-c++-only */
/* %endif */
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/* %if-c++-only */
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

/* %if-c-only */
	b->yy_input_file = file;
/* %endif */
/* %if-c++-only */
/* %endif */
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 145 "mcc.lex"





int column = 0;

void count()
{
	int i;

	for (i = 0; yytext[i] != '\0'; i++)
		if (yytext[i] == '\n')
			column = 0;
		else if (yytext[i] == '\t')
			column += 8 - (column % 8);
		else
			column++;

	ECHO;
}


yy::parser::symbol_type check_type(driver & drv,const std::string & s,const yy::parser::location_type  & loc)
{
/*
* pseudo code --- this is what it should check
*
*	if (yytext == type_name)
*		return(TYPE_NAME);
*
*	retrn(IDENTIFIER);
*/
	auto type_val = drv.GetType(s);
	if(type_val)
	  return yy::parser::make_TYPE_NAME(s,loc);
/*
*	it actually will only return IDENTIFIER
*/
	return make_IDENTIFIER(s,loc);
}
yy::parser::symbol_type make_IDENTIFIER(const std::string & s, const yy::parser::location_type &loc)
{
  return yy::parser::make_IDENTIFIER(s,loc);
}
yy::parser::symbol_type make_STRING_LITERAL(const std::string &s,const yy::parser::location_type&loc)
{
  return yy::parser::make_STRING_LITERAL({mcc::Primitive::Char,1,true,true,false},loc);
}
yy::parser::symbol_type make_CINT(const std::string &s,const yy::parser::location_type&loc)
{
  auto lower = s;
  std::transform(lower.begin(), lower.end(), lower.begin(),
    [](auto c){ return std::tolower(c); });
  if(lower.find("ll")!=std::string::npos && lower.find('u')!=std::string::npos)
    return yy::parser::make_CONSTANT({mcc::Primitive::ULongLong,0,true,true,false},loc);
  if(lower.find("ll")!=std::string::npos)
    return yy::parser::make_CONSTANT({mcc::Primitive::LongLong,0,true,true,false},loc);
  if(lower.find('l')!=std::string::npos&& lower.find('u')!=std::string::npos)
    return yy::parser::make_CONSTANT({mcc::Primitive::ULong,0,true,true,false},loc);
  if(lower.find('u')!=std::string::npos)
    return yy::parser::make_CONSTANT({mcc::Primitive::UInt,0,true,true,false},loc);
  if(lower.find('l')!=std::string::npos)
    return yy::parser::make_CONSTANT({mcc::Primitive::Long,0,true,true,false},loc);
  return yy::parser::make_CONSTANT({mcc::Primitive::Int,0,true,true,false},loc);
}
yy::parser::symbol_type make_CFLOAT(const std::string &s,const yy::parser::location_type&loc)
{
  auto lower = std::tolower(s.back());
  if(lower=='f')
    return yy::parser::make_CONSTANT({mcc::Primitive::Float,0,true,true,false},loc);
  if(lower=='l')
    return yy::parser::make_CONSTANT({mcc::Primitive::LongDouble,0,true,true,false},loc);
return yy::parser::make_CONSTANT({mcc::Primitive::Double,0,true,true,false},loc);



}

void
driver::scan_begin ()
{
  yy_flex_debug = trace_scanning;
  if (file.empty () || file == "-")
    yyin = stdin;
  else if (!(yyin = fopen (file.c_str (), "r")))
    {
      std::cerr << "cannot open " << file << ": " << strerror (errno) << '\n';
      exit (EXIT_FAILURE);
    }
}

void
driver::scan_end ()
{
  fclose (yyin);
}


